"""add attorney email

Revision ID: 1795911ee63e
Revises: f3732c16dbe9
Create Date: 2026-08-28 16:23:52.693284

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.config import get_settings

# revision identifiers, used by Alembic.
revision: str = '1795911ee63e'
down_revision: str | Sequence[str] | None = 'f3732c16dbe9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attorneys', sa.Column('email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###

    # Give the seeded dev admin an email so it actually receives lead
    # notifications too, same opt-in gate as the account itself.
    if get_settings().seed_dev_admin:
        attorneys = sa.table('attorneys', sa.column('username', sa.String()), sa.column('email', sa.String()))
        op.execute(
            attorneys.update()
            .where(attorneys.c.username == 'admin')
            .values(email=get_settings().seed_dev_admin_email)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attorneys', 'email')
    # ### end Alembic commands ###
