"""add attorney auth

Revision ID: f3732c16dbe9
Revises: 9b7ec7e892a0
Create Date: 2026-08-28 15:11:48.536632

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.services.auth import hash_password

# revision identifiers, used by Alembic.
revision: str = 'f3732c16dbe9'
down_revision: str | Sequence[str] | None = '9b7ec7e892a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attorneys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attorneys_username'), 'attorneys', ['username'], unique=True)
    op.create_table('attorney_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('attorney_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attorney_id'], ['attorneys.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_attorney_sessions_attorney_id'), 'attorney_sessions', ['attorney_id'], unique=False)
    # ### end Alembic commands ###

    # Seed a dummy admin/admin attorney so auth works out of the box.
    # Real attorneys can be added later with scripts/create_attorney.py —
    # this row isn't special beyond being first.
    attorneys = sa.table(
        'attorneys',
        sa.column('id', sa.UUID()),
        sa.column('username', sa.String()),
        sa.column('password_hash', sa.String()),
    )
    op.bulk_insert(
        attorneys,
        [
            {
                'id': uuid.uuid4(),
                'username': 'admin',
                'password_hash': hash_password('admin'),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attorney_sessions_attorney_id'), table_name='attorney_sessions')
    op.drop_table('attorney_sessions')
    op.drop_index(op.f('ix_attorneys_username'), table_name='attorneys')
    op.drop_table('attorneys')
    # ### end Alembic commands ###
